import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav
          style={{
            padding: "1rem",
            backgroundColor: "#333",
            color: "white",
            display: "flex",
            gap: "1.5rem",
            alignItems: "center",
            flexWrap: "wrap",
          }}
        >
          <Link
            href="/"
            style={{
              color: "white",
              textDecoration: "none",
              fontWeight: "bold",
            }}
          >
            Home
          </Link>
          <Link
            href="/LAB_20"
            style={{ color: "white", textDecoration: "none" }}
          >
            Lab 20
          </Link>
          <Link
            href="/LAB_21"
            style={{ color: "white", textDecoration: "none" }}
          >
            Lab 21
          </Link>
          <Link
            href="/LAB_22"
            style={{ color: "white", textDecoration: "none" }}
          >
            Lab 22
          </Link>
          <Link
            href="/LAB_23"
            style={{ color: "white", textDecoration: "none" }}
          >
            Lab 23
          </Link>
          <Link
            href="/LAB_24"
            style={{ color: "white", textDecoration: "none" }}
          >
            Lab 24
          </Link>
          <Link
            href="/LAB_25"
            style={{ color: "white", textDecoration: "none" }}
          >
            Lab 25
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
