import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="navbar" style={{ padding: '0.5rem 1rem', background: '#333', display: 'flex', gap: '1rem', flexWrap: 'wrap' }}>
          <Link
            href="/"
            style={{
              color: "white",
              textDecoration: "none",
              fontWeight: "bold",
            }}
          >
            Home
          </Link>
          {[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30].map(n => (
            <Link
              key={n}
              href={`/LAB_${n}`}
              style={{ color: "white", textDecoration: "none", fontSize: '0.9rem' }}
            >
              Lab {n}
            </Link>
          ))}
        </nav>
        {children}
      </body>
    </html>
  );
}
